config/routes.rb
Rails.application.routes.draw do
  
  resources :teams

  resources :pages, only: [:index]
  
  resources :user_sessions, only: [:new, :create, :destroy]
  resources :user_to_team, only: [:update, :destroy]
  resources :users, only: [:index, :new, :create]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "pages#index"
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:new, :create]
  
  def new
    @user = User.new
  end

  def create
    @user = User.find_by(name: params[:user][:name])

    if @user && @user.authenticate(params[:user][:password])
      reset_session
      active_session = @user.active_sessions.create!(user_agent: request.user_agent, ip_address: request.ip)
      session[:current_active_session_id] = active_session.id
      redirect_to root_path
    else
      flash[:alert] = "Login failed"
      redirect_to new_user_session_path
    end
  end

  def destroy
    active_session = ActiveSession.find_by(id: session[:current_active_session_id])
    reset_session
    active_session.destroy! if active_session.present?

    #session[:user_id] = nil
    redirect_to root_path
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/new.html.erb
<h1>Login page</h1>

<div class="zerogrid">
  <div class="col-2-3">
    <div class="contact">
        <div id="contact_form">
        <%= form_with model: @user, id: 'ff', url: user_sessions_path do |f| %>
          <% if @user.errors.any? %>
            <div>
              <ul>
                <% @user.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <label class="row">
            <div class="col-2-2">
              <div class="wrap-col">
                <div>
                  <%= f.label :name %>
                  <%= f.text_field :name %>
                </div>
              </div>
            </div>
          </label>
          <label class="row">
            <div class="col-1-2">
              <div class="wrap-col">
                <div>
                  <%= f.label :password %>
                  <%= f.password_field :password %>
                </div>
              </div>
            </div>
          </label>

          <p>
            <%= f.submit 'Login', class: "sendButton" %>
          </p>
        <% end %>
      </div>
    </div>
  </div>
</div>