config/routes.rb
Rails.application.routes.draw do
  
  resources :teams

  resources :pages, only: [:index]
  
  resources :user_sessions, only: [:new, :create, :destroy]
  resources :user_to_team, only: [:update, :destroy]
  resources :users, only: [:index, :new, :create]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "pages#index"
end

app/views/layouts/_menu.html.erb
    <div class="header">
      <div id='cssmenu' >
        <ul>
         <% if current_user %>
           <li><a><span><%= current_user.name %></span></a></li>

           <!--<li class=' has-sub'><a href='#'><span>Category</span></a>
            <ul>
             <li class='has-sub'><a href='#'><span>Item 1</span></a>
              <ul>
                 <li><a href='#'><span>Sub Item</span></a></li>
                 <li class='last'><a href='#'><span>Sub Item</span></a></li>
              </ul>
             </li>
             <li class='has-sub'><a href='#'><span>Item 2</span></a>
              <ul>
                 <li><a href='#'><span>Sub Item</span></a></li>
                 <li class='last'><a href='#'><span>Sub Item</span></a></li>
              </ul>
             </li>
            </ul>
           </li>-->

           <li><%= link_to 'Users', users_path %></li>
           <li><%= link_to 'Teams', teams_path if current_user.is_leader? %></li>
           <li class='last'><%= link_to 'Log out', user_session_path(current_user), data: { turbo_method: :delete } %></li>
         <% else %>
            <li><%= link_to 'Login', new_user_session_path %></li>
         <% end %>
        </ul>
      </div>
    </div>

   <% flash.each do |type, msg| %>
      <div>
        <%= msg %>
      </div>
   <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Supporter</title>

    <!-- Basic Page Needs
    ================================================== -->
    <meta charset="utf-8">
    <meta name="description" content="TechSupport">
    <meta name="author" content="Jan Padrta">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

<body class="single-page">
  <div class="wrap-body">
    <%= render partial: "layouts/menu" %>

    <!--////////////////////////////////////Container-->
    <section id="container">
      <div class="wrap-container clearfix">
        <div id="main-content">
          <div class="wrap-content">
            <article class="single-post">
              <div class="art-content">
                
                <%= yield %>

              </div>
            </article>
          </div>
        </div>
      </div>
    </section>

    <!--////////////////////////////////////Footer-->
    <footer>
      <div class="copyright">
        <div class="zerogrid wrapper">
          Copyright @ TechSupport - Created by Jan Padrta 
          <ul class="quick-link">
            <li><a href="#">Privacy Policy</a></li>
            <li><a href="#">Terms of Use</a></li>
          </ul>
        </div>
      </div>
    </footer>
  </div>
</body>
</html>